# Generated by Django 2.2.2 on 2019-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190620_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='workout',
            field=models.ManyToManyField(blank=True, related_name='user_workout', to='catalog.Workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(related_name='wrokout_exercise', to='catalog.Exercise'),
        ),
    ]
