# Generated by Django 2.2.2 on 2019-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190620_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='catalog.Userprofile'),
        ),
    ]
