# Generated by Django 2.2.2 on 2019-07-07 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190707_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout',
            field=models.ManyToManyField(blank=True, related_name='user_workout', to='catalog.Workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='catalog.Userprofile'),
        ),
    ]
